/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nordic_tx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1d227aa9169123335554c7962533ad4d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <nordic/nordic_tx.h>
// pydoc.h is automatically generated in the build directory
#include <nordic_tx_pydoc.h>

void bind_nordic_tx(py::module& m)
{

    using nordic_tx    = ::gr::nordic::nordic_tx;


    py::class_<nordic_tx, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<nordic_tx>>(m, "nordic_tx", D(nordic_tx))

        .def(py::init(&nordic_tx::make),
           py::arg("channel_count") = 1,
           D(nordic_tx,make)
        )
        



        ;




}








