/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nordic_rx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d79c171eb31d630d3fd582614fa46e3a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <nordic/nordic_rx.h>
// pydoc.h is automatically generated in the build directory
#include <nordic_rx_pydoc.h>

void bind_nordic_rx(py::module& m)
{

    using nordic_rx    = gr::nordic::nordic_rx;
    
    py::class_<nordic_rx,
               gr::sync_block,
               gr::block,
               gr::basic_block,
        std::shared_ptr<nordic_rx>>(m, "nordic_rx", D(nordic_rx))

        .def(py::init(&nordic_rx::make),
           py::arg("channel") = 0,
           py::arg("address_length") = 5,
           py::arg("crc_length") = 2,
           py::arg("data_rate") = 0,
           D(nordic_rx,make)
        )
        



        ;




}








